# Generated by Django 4.0.6 on 2022-07-22 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('munch', '0002_alter_order_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='OrderModel',
        ),
        migrations.RenameField(
            model_name='ordermodel',
            old_name='created',
            new_name='created_on',
        ),
    ]
