# Generated by Django 4.0.6 on 2022-07-22 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('munch', '0004_ordermodel_city_ordermodel_email_ordermodel_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='zip_code',
            new_name='zip',
        ),
    ]
