# Generated by Django 4.0.6 on 2022-07-23 08:54

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.base


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('munch', '0006_ordermodel_is_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderConfirmation',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=(django.views.generic.base.View, 'auth.user'),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
